package com.yelot.mapper;

import com.yelot.entity.User;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * Created by kee on 17/5/15.
 */
@Mapper
public interface UserMapper {

    @Delete("drop table t_user if exists")
    void dropTable();

    @Insert("create table t_user (id bigint generated by default as identity, password varchar(255), name varchar(255), primary key (id))")
    void createTable();

    @Insert("insert into t_user(name,password) values(#{name},#{password})")
    void insert(User user);

    @Select("select id,name,password from t_user")
    List<User> findAll();

    @Select("select id,name,password from t_user where name like #{name}")
    List<User> findByNameLike(String name);

    @Delete("delete from t_user")
    void deleteAll();

}
