server:
  port: 8081

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/golden_crm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&autoReconnect=true
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver

#spring:
#    datasource:
#        url: jdbc:oracle:thin:@192.168.2.227:1521:BOSCH
#        name: WF
#        password: 123456
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: oracle.jdbc.OracleDriver


mybatis:
  mapperLocations: classpath:dao/*.xml
  typeAliasesPackage: com.yelotot.mapper

logging:
  file: golden_crm.log
